version: "3" 
services:
  db:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    volumes:
      - ".\\volumes\\db_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
        - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: mydb
    volumes:
      - ".\\volumes\\wp_volume:/var/www/html"

volumes:
  mysql: {}